### ISSUE TITLE
The schedule of release

### ISSUE THREAD

**Issue by hangtingchen** [edufonseca/uclser#1]
Any schedule to realise the code? Can't wait to use it.

**Comment by edufonseca** [comment]
Sorry for the delay! We've been so busy with many other things. March is the month. We'll keep you posted.

thanks for your patience!

**Comment by hangtingchen** [comment]
THANKS A LOT Sincerely, Hangting Chen On 02/20/2021 20:12, Eduardo Fonseca wrote: Sorry for the delay! We've been so busy with many other things. March is the month. We'll keep you posted. thanks for your patience! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by edufonseca** [comment]
We just released the code, as well as slides and poster (for ICASSP) and a blog post.  We'll announce it on Monday.

Hope it's useful for your research! 

Please let me know if you can run it smoothly. Thanks

**Comment by hangtingchen** [comment]
Thanks for your reminder. We will test it and give the feedback. Sincerely, Hangting Chen On 05/02/2021 00:31, Eduardo Fonseca wrote: We just released the code, as well as slides and poster (for ICASSP) and a blog post. We'll announce it on Monday. Hope it's useful for your research! Please let me know if you can run it smoothly. Thanks — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
